### ISSUE TITLE
REV Hardware Client won't set any parameters

### ISSUE THREAD

**Issue by GrahamSH-LLK** [wpilibsuite/2025Beta#32]
**Describe the bug**
No parameters can be set on any motor controllers from REV Hardware Client. I have only tested on Spark Maxes.

**To Reproduce**
1. Connect a Spark Max to a computer running the beta version of RHWC with a USB cable
2. Update the firmware to the beta
3. Try to set any parameter (including can ID) 
4. Get error toast "cannot set parameter kCanID" (or whatever parameter you tried to set)

**Expected behavior**
It allows me to configure the controller

**Desktop (please complete the following information if applicable):**
 - OS: Windows 10
 - OS Language: English

**Additional context**
None

**Comment by jfabellera** [comment]
Are you directly connected to the SPARK MAX over USB?

**Comment by GrahamSH-LLK** [comment]
> Are you directly connected to the SPARK MAX over USB?

Yes.

**Comment by NoahAndrews** [comment]
Thank you for the report. This is a SPARK MAX (not Flex) firmware issue that will be fixed in the next firmware beta release. 

It also only affects setting the CAN ID. The reason it appears to affect other parameters is that after you attempt to change the CAN ID, the REV Hardware Client becomes confused about what the device's actual CAN ID is, because it successfully changed the ID, but it thinks that it failed to do so.

If you change the CAN ID and then rescan for devices or restart the REV Hardware Client, setting other parameters should work.

**Comment by GrahamSH-LLK** [comment]
> Thank you for the report. This is a SPARK MAX (not Flex) firmware issue that will be fixed in the next firmware beta release.
> 
> It also only affects setting the CAN ID. The reason it appears to affect other parameters is that after you attempt to change the CAN ID, the REV Hardware Client becomes confused about what the device's actual CAN ID is, because it successfully changed the ID, but it thinks that it failed.
> 
> If you change the CAN ID and then rescan for devices or restart the REV Hardware Client, setting other parameters should work.

Odd, I restarted a bunch of times and it still wouldn't work, but maybe my first step was to try to change the CAN ID. Thanks for the fast fix!
